### ISSUE TITLE
Update document projektplan

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#23]
Document projektplan to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by wikstorm** [comment]
Första versionen klar, bifogar här.
Granskare: @Nibor9198 
[Projektplan_1.1.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6076425/Projektplan_1.1.pdf)

**Comment by Nibor9198** [comment]
### Granskning 1.1

Några kommentarer är lite ospecifika, skriv om du undrar något.
@wikstorm 

[Projektplan_1.1 granskning.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6100892/Projektplan_1.1.granskning.pdf)

**Comment by wikstorm** [comment]
Fixat! Projektet skrivs med litet g, och angående inledande mening så är det som du skriver att det gäller kandidatrapporten. Annars korrigerade jag allt.
[Projektplan_1.2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6106683/Projektplan_1.2.pdf)

**Comment by Nibor9198** [comment]
## Granskning 1.2
### Har bara en kommentarer på 3.3 
I meningen:
_"När detta blivit godkänt kan enpull requestskapas, från funktionsbranchen man arbetar på"_.

Skulle vilja ha något i stil med:

 _"Detta görs genom att det skapas en pullrequest på utvecklingsgrenen för koden från funktionsgrenen som har jobbats på. För att pullrequesten ska bli godkänd..."_
(Kans säkert skrivas lite bättre)


Sen har du fortfarande inte refererat till eller definierat grenstrukturen som vi använder. 

Annars finemang 🤙

**Comment by Nibor9198** [comment]
## Granskning 1.3

GODKÄND
