### ISSUE TITLE
Review introduction for kandidatrapport

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#24]
Introduction to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by DennisBerntsson** [comment]
Första version av introduktionen.
Att kolla på är definitionen för ett gimbal-system, samt hela kapitel 1. Introduktion.
De 3 frågeställningarna som finns är de som givits ut av kursen.

[Virtuell_gimbal_kamera_kandidatrapport.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6077789/Virtuell_gimbal_kamera_kandidatrapport.pdf)

**Comment by wikstorm** [comment]
Definitionen ser bra ut. Här är kommentarerna för övriga delar:
[intro_0.1_granskad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6097076/intro_0.1_granskad.pdf)

**Comment by DennisBerntsson** [comment]
Här är åtgärderna på era kommentarer. Åtgärderna är gulmarkerade.

[Kandidatrapport_intro_reviderad_v1.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6101563/Kandidatrapport_intro_reviderad_v1.pdf)

**Comment by wikstorm** [comment]
Ser bra ut! En sista sak bara, på frågeställning 2 står det "virtuell gimbal-kamerasystem", system ska bort om det är projektnamnet ni syftar på. Annars bra, efter det kan ni sätta som 1.0(eller vad det nu blir)!
