### ISSUE TITLE
Write method for kandidatrapport

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#25]
Method to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by wikstorm** [comment]
Redo för granskning.
@Nibor9198 @emilcw @PeterWickenberg

**Comment by emilcw** [comment]
Då har vi granskat, här kommer den granskade versionen! @AxelGard @DennisBerntsson @aannalarsson 
[Metod_reviderad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6089714/Metod_reviderad.pdf)

**Comment by wikstorm** [comment]
Fixat. Det blev lite konstigt med referenser och ni verkar inte heller fått den senaste versionen. Vi behandlade alla delar, men ni får en ganska annorlunda version, implementationen måste vi se över med Dennis. Levels/subsections osv. Definitionerna är inlagda i definitions.tex, så kolla dem. Här är textdelen iallafall!
[Metoddelen_kandidatrapport_reviderad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6097153/Metoddelen_kandidatrapport_reviderad.pdf)

**Comment by emilcw** [comment]
Vi har tre kommentar till som behöver åtgärdas. Annars ser det bra ut!
@AxelGard @wikstorm @aannalarsson 

[Metoddelen_kandidatrapport_granskad_ver_2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6100725/Metoddelen_kandidatrapport_granskad_ver_2.pdf)

**Comment by wikstorm** [comment]
Åtgärdat allt förutom sista. Det som Axel beskriver angående den texten är att det är något som han satt upp. GitHub har alltså ingen färdig process för att göra detta. Det som beskrivs i texten är ett förtydligande på hur det går till i systemet. Den biten text kan därför antingen vara kvar eller tas bort helt, det är upp till er om ni tycker den är nödvändig eller inte.
[Metoddelen_kandidatrapport_reviderad_2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6101380/Metoddelen_kandidatrapport_reviderad_2.pdf)

**Comment by emilcw** [comment]
@AxelGard @aannalarsson @wikstorm 
Yes, låt den biten vara som den är. Då är den godkänd!
