### ISSUE TITLE
Write document architecture

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#27]
Document architecture to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by AxelGard** [comment]
I made two files one has is marked where changes have been done, but they should be the same information-wise. 


[tddd96_kandidat_arkitektur_dokument.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6077942/tddd96_kandidat_arkitektur_dokument.pdf)
[marked_with_changes_tddd96_kandidat_arkitektur_dokument.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6077943/marked_with_changes_tddd96_kandidat_arkitektur_dokument.pdf)

**Comment by AxelGard** [comment]
@zolo888  @wikstorm

**Comment by wikstorm** [comment]
Korrekturläst:
[arkitektur_1.0_korrekturlast.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6085224/arkitektur_1.0_korrekturlast.pdf)

**Comment by AxelGard** [comment]
The only thing that I did not fix was "behöver systemet kunna kommunicera med andra system än FixHawk." , this will need more thinkging over. I believe the system will need to support more types of autopilot systems but this will need future work. But thanks for bringing it to my attention. :+1:  

[tddd96_kandidat_arkitektur_dokument_fix_av_granskning.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6097181/tddd96_kandidat_arkitektur_dokument_fix_av_granskning.pdf)

**Comment by wikstorm** [comment]
Granskad. Samma punkt som du valde att inkludera kommenterades. Vet att du behöver tänka mer men som det är nu fungerar det inte grammatiskt.
[arkitektur_1.2_granskad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6100690/arkitektur_1.2_granskad.pdf)

**Comment by AxelGard** [comment]
Fixade det nya, var lite osäker på vad ni ville med flödesschemat men gjorde lite antaganden. 

[tddd96_kandidat_arkitektur_dokument_1.3.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6100947/tddd96_kandidat_arkitektur_dokument_1.3.pdf)

**Comment by AxelGard** [comment]
final version. 
[tddd96_kandidat_arkitektur_dokument_2.0.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6101567/tddd96_kandidat_arkitektur_dokument_2.0.pdf)
