### ISSUE TITLE
Write test plan and test report

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#28]
Documents test plan and test report to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by PeterWickenberg** [comment]
[Testrapport_reviderad .pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6083656/Testrapport_reviderad.pdf)
[Testplan_reviderad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6083659/Testplan_reviderad.pdf)

**Comment by emilcw** [comment]
Har fixat till er kommentarer nu. Jag valde att döpa om enhetstestning till modultestning istället för att undvika konflikter med andra def. Jag valde också att inte definera varje modul utan jag säger bara att det går att läsa mer om dem i arkitekturdokumentet. Jag hitta även nån standard för att referera till hemsidor, har dock inte kollat av med Dennis :/

[Testplan rättad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6090588/Testplan.rattad.pdf)
[Testrapport rättad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6090589/Testrapport.rattad.pdf)

**Comment by emilcw** [comment]
@PeterWickenberg @Nibor9198 
Fick som sagt lite input från Lena så har lagt till lite i Testrapporten. Det är enbart avsnitt 3.2 som blivit ändrat så det är inte så mycket. 

[Testrapport_ver2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6102623/Testrapport_ver2.pdf)

**Comment by PeterWickenberg** [comment]
[Testrapport.reviderad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6107920/Testrapport.reviderad.pdf)
[Testplan.reviderad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6107921/Testplan.reviderad.pdf)

**Comment by emilcw** [comment]
@Nibor9198  @PeterWickenberg Fixat revidering.
[Testplan_ver1.3.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6108348/Testplan_ver1.3.pdf)
[Testrapport 0.3.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6108349/Testrapport.0.3.pdf)

**Comment by PeterWickenberg** [comment]
Du måste uppdatera dokumenthistoriken i båda dokumenten. Skicka igen med uppdaterad så kan vi godkänna efter

**Comment by emilcw** [comment]
La till dok-historik
[Testrapport (6).pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6115211/Testrapport.6.pdf)
[Testplan (4).pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6115212/Testplan.4.pdf)

**Comment by PeterWickenberg** [comment]
Godkänd
