### ISSUE TITLE
Write evaluation(utvärdering)

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#29]
Document evaluation to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by wikstorm** [comment]
Första utkast klart, bifogar här.
Granskare: @AxelGard @emilcw 
[Utvardering_0.1.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6076429/Utvardering_0.1.pdf)

**Comment by emilcw** [comment]
Nu har vi granskat den! @wikstorm 

[Utvardering_0.1_granskad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6096858/Utvardering_0.1_granskad.pdf)

**Comment by wikstorm** [comment]
Fixat! Har inte markerat korrigeringar men behandlade alla kommentarer.
[Utvardering_0.2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6096897/Utvardering_0.2.pdf)

**Comment by emilcw** [comment]
Yes, det ser bra ut! Den är godkänd! @wikstorm
