### ISSUE TITLE
Update document kvalitetsplan

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#30]
Document kvalitetsplan to be ready for review by Thursday 13:00

**Comment by aannalarsson** [comment]
Kvalitetsplanen är uppdaterad. Skriver här vilka delar som jag har gjort ändringar i. 

- 3.4 Verktyg -> 3.4.3 KanBan
- 3.6 Utbildning
- 3.7.3 Dokumentation av kod -> 3.7.5 Versionshantering för kod
- 3.8.2 Dokumentgranskning  
- 3.8.3 Kodgranskning -> 3.8.5 Konfigurationshantering av kod
- 4.1 Produktförsäkran -> 5.1 Kontrakt

Granskare: @wikstorm @emilcw 

[Kvalitetsplan_1_1.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6078610/Kvalitetsplan_1_1.pdf)

**Comment by wikstorm** [comment]
Korrekturläst! Här finner du kommentarerna:
[Kvalitetsplan_1_1_korrekturlast.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6082138/Kvalitetsplan_1_1_korrekturlast.pdf)

**Comment by aannalarsson** [comment]
Har fixat alla kommentarer och gulmarkerat alla ändringar!
[Kvalitetsplan_1_2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6083761/Kvalitetsplan_1_2.pdf)

**Comment by emilcw** [comment]
Det ser bra ut! Enda kommentaren är att i 4.1 står det "hälp" och inte "hjälp". Annars är den godkänd!

**Comment by aannalarsson** [comment]
Perfekt, ändrar och lägger upp sen!
