### ISSUE TITLE
Review document kravspecifikation

### ISSUE THREAD

**Issue by wikstorm** [Clear-Sight/virtual-gimbal-camera#31]
Document kravspecifikation to be ready for review by Thursday 13:00

**Comment by wikstorm** [comment]
First review to be returned by Friday 5th 17:00.
Revised version to be returned by Monday 8th 13:00
Review of revised version to be returned by Tuesday 9th 13:00.
Final version to be done by Wednesday 10th 13:00.

**Comment by PeterWickenberg** [comment]
[Kravspecifikation (6).pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6079213/Kravspecifikation.6.pdf)
Bara krav 4 som ändrats. Lade till vilka krav som ska va uppnådda för den

**Comment by aannalarsson** [comment]
Vi började med att granska kravdelen först med upptäckte inkonsekventheter genom kraven. Så vi gjorde en granskning på allt för att göra dokumentet mer konsekvent. 

[Kravspecifikation_reviderad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6082533/Kravspecifikation_reviderad.pdf)

**Comment by DennisBerntsson** [comment]
Yes, jag drar dem tankarna vi hade kring de du tar upp, om jag tolkat något fel så får ni säga till.
Det blev lite längre än tänkt, men det är mest tankar, och inga exakta krav. Om du inte håller med om något så kan vi ta en fortsatt diskussion kring de områdena.

**1.** Angående gimbal så tyckte vi en definition hade varit trevligt då det är ett specialiserat system, så att definitionen mer förklarar vad det är (ifall läsaren inte har koll). T.ex. "Ett system där ett föremål fästs vid ett stöd, som med hjälp av motorer motverkar svängningar. Föremålet upplevs då vara stabilt.". Detta är inget krav, så om det upplevs att förståelsen om vad en gimbal är/gör så kan definitionen utelämnas. Angående kursivering så skulle jag säga att kursivering i övrig text är bra, men i titeln kan det se konstigt ut är min känsla, men det är nog inget fel med det, jag hör gärna @aannalarsson åsikt angående det också.

**2.** Avsnitt 1.2 som du säger definerar vad produkten är, vilket är bra. Dock finns en tvetydighet i delar av texten, t.ex. i definitionen av "APStreamline" står det "Ett videoströmningsverktyg kompatibelt med Fixhawk som har öppen
källkod. Version 2 av produkten används [1].". Vad "Version 2 av produkten används" är oklart vad produkten syftar på i detta läget. Är det version 2 av APStreamline eller version 2 av vår produkt? Det är kring detta vi kände att användandet av ordet "produkten" blev tvetydigt. En lösning på detta skulle vara att förtydliga i texten, där tvetydighet finns, vad produkten syftar på i den instansen. Alternativt som du föreslog att definiera produkten som VGC och skriva det när du hänvisar till produkten (vår produkt).

**3.** Det handlade mest om att förtydliga hur uppkopplingen begränsar systemet. T.ex. är det pålitligheten på uppkopplingen (bra uptime, dålig uptime etc.), är det hastigheten på uppkopplingen eller något annat? Som jag förstår det av din kommentar handlar det mer om tillgängligheten på servern. Det är en svår begränsning att beskriva på ett tydligt sätt då det inte är bara serverns uppkoppling som påverkar, utan det är ju alla inblandade uppkopplingar. Jag har tyvärr inget bra förslag på hur man skulle kunna skriva det i nuläget.

**Comment by PeterWickenberg** [comment]
Tack för svaret. Skriver vad jag tänker göra då

1. Kursiverar gimbal. Som du säger ska inte titeln vara kursiv. Sätter inte namnet kursiv någon stans då det är ett namn.
2. Kommer förtydliga de ställen där produkten kan syfta på flera ställen
3. Visserligen är det jag skrivit rätt vagt. men det är även för att jag egentligen menar alla problem som kan uppkomma av att servern har problem om du förstår vad jag menar. tror inte jag ändrar något där om ni inte verkligen vill det.

**Comment by PeterWickenberg** [comment]
[Kravspecifikation1.2.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6089581/Kravspecifikation1.2.pdf)
Här har ni i alla fal den nya. Jag har behandlat alla kommentarer med undantag för de tre fallen jag pratat om innan.

**Comment by aannalarsson** [comment]
Vi har granskat version 1.2 nu! 

[Kravspecifikation1.2_granskad.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6106627/Kravspecifikation1.2_granskad.pdf)

**Comment by PeterWickenberg** [comment]
Har reviderat era kommentarer men gjorde även ett par andra saker
1. 3.3 har fått ett nytt namn(Lena som ville detta)
2. Rymdkoordinater -> koordinater(konsekvent)
3. Koordinater -> koordinat(eftersom det endast är en koordinat som används åt gången)
[Kravspecifikation_1_3.pdf](https://github.com/Clear-Sight/virtual-gimbal-camera/files/6107016/Kravspecifikation_1_3.pdf)

**Comment by aannalarsson** [comment]
Ser jättebra ut, det är godkänt!
