### ISSUE TITLE
View Controller args to camera filter args not corresponding 

### ISSUE THREAD

**Issue by AxelGard** [Clear-Sight/virtual-gimbal-camera#55]
Clear miss-communication cross teams. This needs to be fixed. 
CamraFilter.update takes different args then viewcontroller wants to set. 
check out the pipeline for this colide.  
[code](https://github.com/Clear-Sight/virtual-gimbal-camera/compare/intgration-fixes)

**Comment by AxelGard** [comment]
Okej so I @wikstorm  told me that the args should be the other way around but Zoom is still not fixed @Nibor9198

**Comment by emilcw** [comment]
Solved.
