### ISSUE TITLE
Review pipeline.py and log.py

### ISSUE THREAD

**Issue by emilcw** [Clear-Sight/virtual-gimbal-camera#90]
Pipeline.py:
Run pylint and fix issues. Docstrings for module is of most importance and that the class docstring contains all the methods. 

Log.py:
Run pylint and fix issues. 

If you don't fix something, clearly motivate your decision.

**Comment by AxelGard** [comment]
fixed in demo srs

**Comment by emilcw** [comment]
Looks good!
